; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC on Mon Mar 15 2021 13:39:37 GMT+0800 (Taipei Standard Time)

M106 S0